In [110]:
import pandas as pd
import numpy as np
import re

In [111]:
df = pd.read_csv("ML1404_dataset - ML1404_dataset.csv")

In [112]:
df

,first_name,last_name,headline,job_title,time_type_full_or_part,duration_of_cooperation,location_hybrid,company_name
0,Mohammad,Khezri,SEO Specialist,Search Engine Optimization Specialist,Pixune · Freelance,Jul 2022 - Present · 2 yrs 1 mo,Poland · Remote,NaN
1,mohamad,Imani,Sales manager at Classic Decoration,Search Engine Optimization Manager,Cofinfo · Self-employed,Dec 2022 - Present · 1 yr 8 mos,NaN,NaN
2,Azin,Ehsanian,Content Marketer at bonmano,Search Engine Optimization Specialist,Karnakon · Full-time,Dec 2020 - Aug 2022 · 1 yr 9 mos,"Tehran, Iran",NaN
3,Mahdi,Bagheri,Attorney at Law | 9 Years of experience,Trader,Forex Trading Online · Apprenticeship,Apr 2020 - Present · 4 yrs 4 mos,NaN,Forex Trading Online
4,Sara,Sadeghi,Warranty senior expert at Arian Motor Co.,In personal marketing,Home Design Decoration ideas · Part-time,Jan 2018 - Present · 6 yrs 7 mos,"Shiraz County, Fars, Iran",Home Design Decoration ideas
...,...,...,...,...,...,...,...,...
12995,Amir,Jafari,Talent Acquisition and People Partner,sales & marketing supervisor in renew transpor...,Mammut Diesel (Exclusive Partner of Scania Tru...,Oct 2004 - Present · 19 yrs 11 mos,"Tehran, Iran",NaN
12996,Mahdi,Momeni,Frontend Engineer at Digikala,Sales Manager,Mammut World Panel Conex · Full-time,Oct 2004 - Present · 19 yrs 11 mos,Iran · On-site,Mammut Structures & Panel
12997,Fateme,Najafi,Sr. Data Scientist @ Theory+Practice | Data An...,sales & marketing supervisor in prefabricated ...,Mammut group,Jul 2003 - Present · 21 yrs 2 mos,"Alborz Province, Iran",NaN
12998,Mohammad,Ahmadzadeh,Cybersecurity Researcher | Penetration Test,Founder,SQUARED inc.,Sep 2023 - Present · 1 yr,"Ontario, Canada",SQUARED inc.
12999,Ahmad,Abbasi,Product Designer @ Mofid Securities | Design S...,Founder,19 Group,May 2022 - Present · 2 yrs 4 mos,International,19 Group

In [113]:
df[df['duration_of_cooperation'].isnull()==True]

,first_name,last_name,headline,job_title,time_type_full_or_part,duration_of_cooperation,location_hybrid,company_name
11,sadegh,farahani,--,Chidaneh,Full-time · 2 yrs 8 mos,NaN,NaN,Chidaneh
24,Ava,Amirfazli,Offline Marketing Specialist,Chidaneh,Full-time · 2 yrs 8 mos,NaN,NaN,Chidaneh
37,Bita,Farahani,Physical Chemistry,Chidaneh,Full-time · 2 yrs 8 mos,NaN,NaN,Chidaneh
54,Pariya,Sayadi,performance specialist at @digikala.com,Mobinnet,13 yrs 4 mos,NaN,NaN,mobinnet|مبین‌نت
56,Seyed Mohsen,Zarei,Technical Specialist at Tunnel Sadd Ariana Com...,Simaresana Co.,5 yrs,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
12958,mohamad saleh,shojai,student ce sharif,TondAhil,Self-employed · 4 mos,NaN,NaN,TondAhil
12966,Abolfazl,Talaei,Software Engineer @ Digikala,Sayesaman.Co,Full-time · 7 yrs 11 mos,NaN,NaN,Sayesaman.Co
12969,Sina,Dehghanian,‪Data Analyst & Engineer | Python Hobbyist | e...,Deputy Complex manager,Arak Petrochemical Company,NaN,NaN,Arak Petrochemical Company
12982,EU MDR,Compliance,Take control of medical device compliance | Te...,Behpardaz Hamrah Samaneh Aval (Behsa),5 yrs 9 mos,NaN,NaN,Behpardaz Hamrah Samaneh Aval (Behsa)
12987,Parand,Mousavi,Principal Software Engineer,Mico Groups,6 yrs 2 mos,NaN,NaN,Mico Groups

In [114]:
df

,first_name,last_name,headline,job_title,time_type_full_or_part,duration_of_cooperation,location_hybrid,company_name
0,Mohammad,Khezri,SEO Specialist,Search Engine Optimization Specialist,Pixune · Freelance,Jul 2022 - Present · 2 yrs 1 mo,Poland · Remote,NaN
1,mohamad,Imani,Sales manager at Classic Decoration,Search Engine Optimization Manager,Cofinfo · Self-employed,Dec 2022 - Present · 1 yr 8 mos,NaN,NaN
2,Azin,Ehsanian,Content Marketer at bonmano,Search Engine Optimization Specialist,Karnakon · Full-time,Dec 2020 - Aug 2022 · 1 yr 9 mos,"Tehran, Iran",NaN
3,Mahdi,Bagheri,Attorney at Law | 9 Years of experience,Trader,Forex Trading Online · Apprenticeship,Apr 2020 - Present · 4 yrs 4 mos,NaN,Forex Trading Online
4,Sara,Sadeghi,Warranty senior expert at Arian Motor Co.,In personal marketing,Home Design Decoration ideas · Part-time,Jan 2018 - Present · 6 yrs 7 mos,"Shiraz County, Fars, Iran",Home Design Decoration ideas
...,...,...,...,...,...,...,...,...
12995,Amir,Jafari,Talent Acquisition and People Partner,sales & marketing supervisor in renew transpor...,Mammut Diesel (Exclusive Partner of Scania Tru...,Oct 2004 - Present · 19 yrs 11 mos,"Tehran, Iran",NaN
12996,Mahdi,Momeni,Frontend Engineer at Digikala,Sales Manager,Mammut World Panel Conex · Full-time,Oct 2004 - Present · 19 yrs 11 mos,Iran · On-site,Mammut Structures & Panel
12997,Fateme,Najafi,Sr. Data Scientist @ Theory+Practice | Data An...,sales & marketing supervisor in prefabricated ...,Mammut group,Jul 2003 - Present · 21 yrs 2 mos,"Alborz Province, Iran",NaN
12998,Mohammad,Ahmadzadeh,Cybersecurity Researcher | Penetration Test,Founder,SQUARED inc.,Sep 2023 - Present · 1 yr,"Ontario, Canada",SQUARED inc.
12999,Ahmad,Abbasi,Product Designer @ Mofid Securities | Design S...,Founder,19 Group,May 2022 - Present · 2 yrs 4 mos,International,19 Group

In [115]:
import re
import pandas as pd

pattern = re.compile(
    r'(\d+\s*(?:yr|yrs))?(\s*\d+\s*mos)?',
    flags=re.IGNORECASE
)

def matches_experience_pattern(value):
    if pd.isnull(value):
        return False
    matches = pattern.findall(str(value))
    return any('yr' in match[0].lower() or 'mos' in match[1].lower() for match in matches if match)

In [116]:
for c in df.columns:
    matched_rows = df[df[c].apply(matches_experience_pattern)]
    print('\n###################################\n',f'for {c} \n',matched_rows[['first_name', 'last_name', 'time_type_full_or_part','duration_of_cooperation']])

###################################
 for first_name
 Empty DataFrame
Columns: [first_name, last_name, time_type_full_or_part, duration_of_cooperation]
Index: []

###################################
 for last_name
 Empty DataFrame
Columns: [first_name, last_name, time_type_full_or_part, duration_of_cooperation]
Index: []

###################################
 for headline
       first_name last_name time_type_full_or_part  \
11893    Nazanin  Teymoori              ZagStudio

              duration_of_cooperation
11893  Mar 2013 - 2018 · 4 yrs 11 mos

###################################
 for job_title
 Empty DataFrame
Columns: [first_name, last_name, time_type_full_or_part, duration_of_cooperation]
Index: []

###################################
 for time_type_full_or_part
          first_name    last_name    time_type_full_or_part  \
11           sadegh     farahani   Full-time · 2 yrs 8 mos
24              Ava    Amirfazli   Full-time · 2 yrs 8 mos
37             Bita     Farahani   Full-time · 2 yrs 8 mos
54           Pariya       Sayadi              13 yrs 4 mos
56     Seyed Mohsen        Zarei                     5 yrs
...             ...          ...                       ...
12960       Hossein      Sadeghi  Full-time · 4 yrs 10 mos
12966      Abolfazl       Talaei  Full-time · 7 yrs 11 mos
12973        Pouria      Darbani   Part-time · 3 yrs 2 mos
12982       EU MDR   Compliance                5 yrs 9 mos
12987        Parand      Mousavi               6 yrs 2 mos

      duration_of_cooperation
11                        NaN
24                        NaN
37                        NaN
54                        NaN
56                        NaN
...                       ...
12960                 On-site
12966                     NaN
12973            Tehran, Iran
12982                     NaN
12987                     NaN

[1578 rows x 4 columns]

###################################
 for duration_of_cooperation
       first_name   last_name  \
0       Mohammad      Khezri
1        mohamad       Imani
2           Azin    Ehsanian
3          Mahdi     Bagheri
4           Sara     Sadeghi
...          ...         ...
12995       Amir      Jafari
12996      Mahdi      Momeni
12997     Fateme      Najafi
12998   Mohammad  Ahmadzadeh
12999     Ahmad       Abbasi

                                  time_type_full_or_part  \
0                                     Pixune · Freelance
1                                Cofinfo · Self-employed
2                                   Karnakon · Full-time
3                  Forex Trading Online · Apprenticeship
4               Home Design Decoration ideas · Part-time
...                                                  ...
12995  Mammut Diesel (Exclusive Partner of Scania Tru...
12996               Mammut World Panel Conex · Full-time
12997                                       Mammut group
12998                                       SQUARED inc.
12999                                           19 Group

                  duration_of_cooperation
0         Jul 2022 - Present · 2 yrs 1 mo
1         Dec 2022 - Present · 1 yr 8 mos
2        Dec 2020 - Aug 2022 · 1 yr 9 mos
3        Apr 2020 - Present · 4 yrs 4 mos
4        Jan 2018 - Present · 6 yrs 7 mos
...                                   ...
12995  Oct 2004 - Present · 19 yrs 11 mos
12996  Oct 2004 - Present · 19 yrs 11 mos
12997   Jul 2003 - Present · 21 yrs 2 mos
12998           Sep 2023 - Present · 1 yr
12999    May 2022 - Present · 2 yrs 4 mos

[11141 rows x 4 columns]

###################################
 for location_hybrid
 Empty DataFrame
Columns: [first_name, last_name, time_type_full_or_part, duration_of_cooperation]
Index: []

###################################
 for company_name
 Empty DataFrame
Columns: [first_name, last_name, time_type_full_or_part, duration_of_cooperation]
Index: []

In [117]:
11141 + 1578

12719

In [118]:
df.iloc[11893]

first_name                                                           Nazanin
last_name                                                           Teymoori
headline                   Tech SEO Executive with +6 yrs Exp | Consultin...
job_title                                                 Founder & Designer
time_type_full_or_part                                             ZagStudio
duration_of_cooperation                       Mar 2013 - 2018 · 4 yrs 11 mos
location_hybrid                                                 Iran, Tehran
company_name                                                       ZagStudio
Name: 11893, dtype: object

In [119]:
df.iloc[12960]

first_name                                                       Hossein
last_name                                                        Sadeghi
headline                   CEO at Pardazeshgaran Behin Sayar (sayar.org)
job_title                                                     Ebrahim Co
time_type_full_or_part                          Full-time · 4 yrs 10 mos
duration_of_cooperation                                          On-site
location_hybrid                                                      NaN
company_name                                  Ebrahim Co. Ltd. | ابراهیم
Name: 12960, dtype: object

In [120]:

def is_valid_duration(value):
    if pd.isna(value):
        return False
    return bool(pd.Series(value).str.contains(r'\d+\s(yr|yrs|mos|mo)', regex=True).iloc[0])

df['duration_of_cooperation'] = df.apply(
    lambda row: row['time_type_full_or_part'] if not is_valid_duration(row['duration_of_cooperation']) else row['duration_of_cooperation'],
    axis=1
)

C:\Users\hwi\AppData\Local\Temp\ipykernel_9932\3252874121.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  return bool(pd.Series(value).str.contains(r'\d+\s(yr|yrs|mos|mo)', regex=True).iloc[0])

In [121]:
    matched_rows = df[df['duration_of_cooperation'].apply(matches_experience_pattern)]
    print(matched_rows[['first_name', 'last_name', 'time_type_full_or_part','duration_of_cooperation']])

      first_name   last_name  \
0       Mohammad      Khezri
1        mohamad       Imani
2           Azin    Ehsanian
3          Mahdi     Bagheri
4           Sara     Sadeghi
...          ...         ...
12995       Amir      Jafari
12996      Mahdi      Momeni
12997     Fateme      Najafi
12998   Mohammad  Ahmadzadeh
12999     Ahmad       Abbasi

                                  time_type_full_or_part  \
0                                     Pixune · Freelance
1                                Cofinfo · Self-employed
2                                   Karnakon · Full-time
3                  Forex Trading Online · Apprenticeship
4               Home Design Decoration ideas · Part-time
...                                                  ...
12995  Mammut Diesel (Exclusive Partner of Scania Tru...
12996               Mammut World Panel Conex · Full-time
12997                                       Mammut group
12998                                       SQUARED inc.
12999                                           19 Group

                  duration_of_cooperation
0         Jul 2022 - Present · 2 yrs 1 mo
1         Dec 2022 - Present · 1 yr 8 mos
2        Dec 2020 - Aug 2022 · 1 yr 9 mos
3        Apr 2020 - Present · 4 yrs 4 mos
4        Jan 2018 - Present · 6 yrs 7 mos
...                                   ...
12995  Oct 2004 - Present · 19 yrs 11 mos
12996  Oct 2004 - Present · 19 yrs 11 mos
12997   Jul 2003 - Present · 21 yrs 2 mos
12998           Sep 2023 - Present · 1 yr
12999    May 2022 - Present · 2 yrs 4 mos

[12719 rows x 4 columns]

In [122]:

def is_valid_duration(value):
    if pd.isna(value):
        return False
    return bool(pd.Series(value).str.contains(r'\d+\s*(yr|yrs|mo|mos)', regex=True).iloc[0])

invalid_durations = df[~df['duration_of_cooperation'].apply(is_valid_duration)]
print(f"invalid_durations {len(invalid_durations)}")

C:\Users\hwi\AppData\Local\Temp\ipykernel_9932\2896877962.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  return bool(pd.Series(value).str.contains(r'\d+\s*(yr|yrs|mo|mos)', regex=True).iloc[0])

invalid_durations 187

In [123]:
df[df['duration_of_cooperation'].isnull()==True]

,first_name,last_name,headline,job_title,time_type_full_or_part,duration_of_cooperation,location_hybrid,company_name
96,Mahdi,Haghighat,Senior Data Engineer | Senior Java Developer |...,NaN,NaN,NaN,NaN,NaN
97,Mehran,Khorrami,Senior Front-end Developer | Full Stack Web De...,NaN,NaN,NaN,NaN,NaN
804,Shaghayegh,Heydari,Software System Analyst,NaN,NaN,NaN,NaN,NaN
990,Samira,Dadashi,Product manager,NaN,NaN,NaN,NaN,NaN
1811,Hamid,Parsa,Broker at Century 21 Atria Top Choice Team,Amutor,NaN,NaN,NaN,NaN
1812,Shima,Sedghi,Forex Trader,Amutor,NaN,NaN,NaN,NaN
1813,AmirMohsen,KarimiMajd,Senior Product Manager,Amutor,NaN,NaN,NaN,NaN
4965,Seied Mostafa,Mirmahdi,strategy manager,NaN,NaN,NaN,NaN,NaN
7553,Milad,Bafarassat,Ex-Tech Product Manager | Transitioning to Com...,expert,NaN,NaN,NaN,NaN
8044,Mohadese,Nemati,Business Analyst supervisor at SnappFood,expert,NaN,NaN,NaN,NaN
8935,hadi,moradi,Senior software developer | Java | Spring boot...,expert,NaN,NaN,NaN,NaN
9438,Behnam,Khakbaz,Finance Services Product Development/ B2B Paym...,expert,NaN,NaN,NaN,NaN
10340,Hamid,Jafari,"SEO Specialist , Digital Marketing , Soft Skills",expert,NaN,NaN,NaN,NaN
10849,Lina,Nygren,Vice Head of Client Success & Segment owner B2...,expert,NaN,NaN,NaN,NaN
12806,Sara,Alimardani,Ui/Ux Designer | User Interface Design,expert,NaN,NaN,NaN,NaN

In [124]:
df = df.dropna(subset=['duration_of_cooperation'])

In [125]:
df['duration_of_cooperation']

0           Jul 2022 - Present · 2 yrs 1 mo
1           Dec 2022 - Present · 1 yr 8 mos
2          Dec 2020 - Aug 2022 · 1 yr 9 mos
3          Apr 2020 - Present · 4 yrs 4 mos
4          Jan 2018 - Present · 6 yrs 7 mos
                        ...
12995    Oct 2004 - Present · 19 yrs 11 mos
12996    Oct 2004 - Present · 19 yrs 11 mos
12997     Jul 2003 - Present · 21 yrs 2 mos
12998             Sep 2023 - Present · 1 yr
12999      May 2022 - Present · 2 yrs 4 mos
Name: duration_of_cooperation, Length: 12985, dtype: object

In [126]:
def is_valid_duration(value):
    if pd.isna(value):
        return False
    pattern = r'(\d+\s*(yr|yrs|mo|mos))'
    return bool(re.search(pattern, str(value)))

invalid_rows = df[~df['duration_of_cooperation'].apply(is_valid_duration)]

print(invalid_rows[['duration_of_cooperation','first_name','time_type_full_or_part']])

                           duration_of_cooperation     first_name  \
66                                            SITS        Sepehr
90                             Irangan · Full-time          shima
95     Varanegar Pishro | ورانگر پیشرو · Full-time          Mahsa
265                             Amazon · Part-time           Omid
442                             پردازشگران نواندیش  Mohammad Reza
...                                            ...            ...
12597                                         Fava         Nasrin
12720                               tadbir company           Omid
12805                                 organization         Shayan
12831                    Sana Andisheh · Full-time         Marjan
12969                   Arak Petrochemical Company           Sina

                            time_type_full_or_part
66                                            SITS
90                             Irangan · Full-time
95     Varanegar Pishro | ورانگر پیشرو · Full-time
265                             Amazon · Part-time
442                             پردازشگران نواندیش
...                                            ...
12597                                         Fava
12720                               tadbir company
12805                                 organization
12831                    Sana Andisheh · Full-time
12969                   Arak Petrochemical Company

[172 rows x 3 columns]

In [127]:
df.iloc[66]

first_name                                                      Sepehr
last_name                                                       Saghari
headline                   CEO & Co-founder at Nimaad | Medical Devices
job_title                                       Virtualization Engineer
time_type_full_or_part                                             SITS
duration_of_cooperation                                            SITS
location_hybrid                                                     NaN
company_name                                                       SITS
Name: 66, dtype: object

In [128]:
df.columns

Index(['first_name', 'last_name', 'headline', 'job_title',
       'time_type_full_or_part', 'duration_of_cooperation', 'location_hybrid',
       'company_name'],
      dtype='object')

In [129]:
df_cleaned = df[df['duration_of_cooperation'].apply(is_valid_duration)]

In [130]:
df_cleaned

,first_name,last_name,headline,job_title,time_type_full_or_part,duration_of_cooperation,location_hybrid,company_name
0,Mohammad,Khezri,SEO Specialist,Search Engine Optimization Specialist,Pixune · Freelance,Jul 2022 - Present · 2 yrs 1 mo,Poland · Remote,NaN
1,mohamad,Imani,Sales manager at Classic Decoration,Search Engine Optimization Manager,Cofinfo · Self-employed,Dec 2022 - Present · 1 yr 8 mos,NaN,NaN
2,Azin,Ehsanian,Content Marketer at bonmano,Search Engine Optimization Specialist,Karnakon · Full-time,Dec 2020 - Aug 2022 · 1 yr 9 mos,"Tehran, Iran",NaN
3,Mahdi,Bagheri,Attorney at Law | 9 Years of experience,Trader,Forex Trading Online · Apprenticeship,Apr 2020 - Present · 4 yrs 4 mos,NaN,Forex Trading Online
4,Sara,Sadeghi,Warranty senior expert at Arian Motor Co.,In personal marketing,Home Design Decoration ideas · Part-time,Jan 2018 - Present · 6 yrs 7 mos,"Shiraz County, Fars, Iran",Home Design Decoration ideas
...,...,...,...,...,...,...,...,...
12995,Amir,Jafari,Talent Acquisition and People Partner,sales & marketing supervisor in renew transpor...,Mammut Diesel (Exclusive Partner of Scania Tru...,Oct 2004 - Present · 19 yrs 11 mos,"Tehran, Iran",NaN
12996,Mahdi,Momeni,Frontend Engineer at Digikala,Sales Manager,Mammut World Panel Conex · Full-time,Oct 2004 - Present · 19 yrs 11 mos,Iran · On-site,Mammut Structures & Panel
12997,Fateme,Najafi,Sr. Data Scientist @ Theory+Practice | Data An...,sales & marketing supervisor in prefabricated ...,Mammut group,Jul 2003 - Present · 21 yrs 2 mos,"Alborz Province, Iran",NaN
12998,Mohammad,Ahmadzadeh,Cybersecurity Researcher | Penetration Test,Founder,SQUARED inc.,Sep 2023 - Present · 1 yr,"Ontario, Canada",SQUARED inc.
12999,Ahmad,Abbasi,Product Designer @ Mofid Securities | Design S...,Founder,19 Group,May 2022 - Present · 2 yrs 4 mos,International,19 Group

In [137]:
import pandas as pd

df = df.copy()

# تمیز کردن dashها، فاصله‌ها، و normalize کردن Present
df.loc[:, 'duration_of_cooperation_clean'] = (
    df['duration_of_cooperation']
      .str.replace('[–—−]', '-', regex=True)        # انواع dash
      .str.replace('\s+', ' ', regex=True)          # حذف فاصله‌های اضافی
      .str.replace('(?i)present', 'Present', regex=True)  # نرمال‌سازی Present
      .str.strip()
)

# الگو برای استخراج سه بخش
pattern = r'(?P<start>[A-Za-z]{3} \d{4})\s*-\s*(?P<end>Present|[A-Za-z]{3} \d{4})\s*[·•]\s*(?P<duration>.+)'

# استخراج مقادیر
extracted = df['duration_of_cooperation_clean'].str.extract(pattern)

# افزودن ستون‌ها
df.loc[:, 'start'] = pd.to_datetime(extracted['start'], format='%b %Y', errors='coerce')
df.loc[:, 'end'] = extracted['end'].replace('Present', pd.NaT)
df.loc[:, 'end'] = pd.to_datetime(df['end'], format='%b %Y', errors='coerce')
df.loc[:, 'duration'] = extracted['duration']

<>:9: SyntaxWarning: invalid escape sequence '\s'
<>:9: SyntaxWarning: invalid escape sequence '\s'
C:\Users\hwi\AppData\Local\Temp\ipykernel_9932\4160502458.py:9: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+', ' ', regex=True)          # حذف فاصله‌های اضافی

In [145]:
df.sample(22)

,first_name,last_name,headline,job_title,time_type_full_or_part,duration_of_cooperation,location_hybrid,company_name,duration_of_cooperation_clean,start,end,duration
870,Mohammad Mahdi,Niazi,Front-end Developer,Computer Technician,Iran film sabet,Dec 2015 - Apr 2018 · 2 yrs 5 mos,NaN,NaN,Dec 2015 - Apr 2018 · 2 yrs 5 mos,2015-12-01,2018-04-01,2 yrs 5 mos
10934,Kieran,Antill,Exec. Director Brand @ Ne-Lo Business Design &...,Software Architect / Senior Nodejs Developer,Cheshmak,Jan 2018 - Apr 2018 · 4 mos,NaN,NaN,Jan 2018 - Apr 2018 · 4 mos,2018-01-01,2018-04-01,4 mos
2320,Reza,Mirabrishami,Actively Seeking SOC Analyst & Cybersecurity C...,Technical R&D,Aris System,Sep 2010 - Sep 2011 · 1 yr 1 mo,Iran,Aris System,Sep 2010 - Sep 2011 · 1 yr 1 mo,2010-09-01,2011-09-01,1 yr 1 mo
1388,Mohammad Javad Nazarzadeh,محمدجواد نظرزاده,مدیرکل لجستیک و توزیع وزارت صمت\nمدرس دانشگاه\...,Graphic Designer,Arman Taymaz Aras Corp · Part-time,Feb 2009 - Nov 2011 · 2 yrs 10 mos,"Tehran,Iran",NaN,Feb 2009 - Nov 2011 · 2 yrs 10 mos,2009-02-01,2011-11-01,2 yrs 10 mos
11233,AmirHossein,Jafari,Android Developer,Senior Sales Executive & Transportation & Dist...,Robat Company · Full-time,Sep 2020 - Feb 2021 · 6 mos,"Tehran, Iran",Robat Company,Sep 2020 - Feb 2021 · 6 mos,2020-09-01,2021-02-01,6 mos
2833,Pouria,Moradi,Market Research Supervisor at Alifard (Sunich),DevOps Engineer,Nextera · Full-time,Jan 2023 - Mar 2024 · 1 yr 3 mos,NaN,Nextera,Jan 2023 - Mar 2024 · 1 yr 3 mos,2023-01-01,2024-03-01,1 yr 3 mos
10619,Mohamad,Ansari,Electrical Engineer,Founder,Alamto.com · Full-time,Oct 2009 - Jan 2022 · 12 yrs 4 mos,iran,NaN,Oct 2009 - Jan 2022 · 12 yrs 4 mos,2009-10-01,2022-01-01,12 yrs 4 mos
5070,Sahar,Ebrahimi,Content specialist,Business Development Manager,MoonXBT Global · Contract,Feb 2023 - Dec 2023 · 11 mos,Remote,MoonXBT Global,Feb 2023 - Dec 2023 · 11 mos,2023-02-01,2023-12-01,11 mos
8595,Destiny,Y.,Database Administrator and Cloud Engineer,KARPIRA International Recruitment Agency,12 yrs 1 mo,12 yrs 1 mo,NaN,KARPIRA International Recruitment Agency,12 yrs 1 mo,NaT,NaT,NaN
9477,Marjan,Zamani,User Experience Designer at Amazon,Innovation Consultant,mobinland · Part-time,Sep 2018 - Mar 2020 · 1 yr 7 mos,"Tehran, Iran",NaN,Sep 2018 - Mar 2020 · 1 yr 7 mos,2018-09-01,2020-03-01,1 yr 7 mos
8101,Alireza,Sadeghi-Nasab,Product Manager | Software PhD Candidate,Software Programmer,Fap,Aug 2008 - Apr 2010 · 1 yr 9 mos,Mashhad,NaN,Aug 2008 - Apr 2010 · 1 yr 9 mos,2008-08-01,2010-04-01,1 yr 9 mos
4073,Aliyar,Yari,Ui Ux Designer at Rayanik,Sales&Support Team Lead,Quera · Full-time,Feb 2024 - Present · 6 mos,"Tehran, Tehran Province, Iran · Hybrid",Quera,Feb 2024 - Present · 6 mos,2024-02-01,NaT,6 mos
9121,Faydim,Sadri,.,Senior Software Engineering Lead (Manager),Microsoft,Dec 2018 - Present · 5 yrs 9 mos,"Vancouver, British Columbia, Canada",Microsoft,Dec 2018 - Present · 5 yrs 9 mos,2018-12-01,NaT,5 yrs 9 mos
7275,Farhad,Esmaeelnejad,B2B Sales Manager at Golrang Industrial group(...,Senior Software Engineering Lead (Manager),Microsoft,Dec 2018 - Present · 5 yrs 9 mos,"Vancouver, British Columbia, Canada",Microsoft,Dec 2018 - Present · 5 yrs 9 mos,2018-12-01,NaT,5 yrs 9 mos
9939,H,Azadbakht,CEO at OmidNet,Product Manager,irasography · Full-time,Jan 2021 - Sep 2021 · 9 mos,"Tehran, Tehran, Iran",irasography,Jan 2021 - Sep 2021 · 9 mos,2021-01-01,2021-09-01,9 mos
943,Nahid,Darehshoori,UI/UX Designer,iOS Developer,SEPEHR Intelligent Technology and Solutions · ...,Sep 2020 - Present · 3 yrs 11 mos,NaN,SEPEHR Intelligent Technology and Solutions,Sep 2020 - Present · 3 yrs 11 mos,2020-09-01,NaT,3 yrs 11 mos
6919,Fateme,Molaei,Senior Front end developer,Executive Assitant to Iran & Turkey President,Ericsson · Full-time,Mar 2017 - Jan 2023 · 5 yrs 11 mos,"Tehran Province, Iran",Ericsson,Mar 2017 - Jan 2023 · 5 yrs 11 mos,2017-03-01,2023-01-01,5 yrs 11 mos
7731,Amir,Ghaffari,M.Sc Student in Futures Studies at University ...,Software Engineer,Navaco,May 2011 - Dec 2012 · 1 yr 8 mos,NaN,NaN,May 2011 - Dec 2012 · 1 yr 8 mos,2011-05-01,2012-12-01,1 yr 8 mos
8107,Farzaneh,Mehrabi,HR Specialist (jr),DPI Co.,Full-time · 8 yrs 2 mos,Full-time · 8 yrs 2 mos,NaN,DPI Co.,Full-time · 8 yrs 2 mos,NaT,NaT,NaN
7952,Mohammad H.,Motevasseli,HRBP@Digikala | Life & Professional Coach | St...,Process Engineer,ENERCHIMI Eng. co.,May 2013 - Jan 2016 · 2 yrs 9 mos,"Tehran Province, Iran",NaN,May 2013 - Jan 2016 · 2 yrs 9 mos,2013-05-01,2016-01-01,2 yrs 9 mos
5760,Maryam,Mahmudimanesh,Process safety engineer at Nargan Co.,Social Media Expert - Social Media PR- Social ...,Shaden Pezhvak Publications · Full-time,Jul 2018 - Feb 2020 · 1 yr 8 mos,"Tehran, Iran",NaN,Jul 2018 - Feb 2020 · 1 yr 8 mos,2018-07-01,2020-02-01,1 yr 8 mos
9245,Seyyed Mohammad Amir,Mirfattah,Learning Facilitation Manager at Orchid Pharmed,Junior executive,Rasa consultant co,Sep 2013 - Mar 2014 · 7 mos,Tehran-Iran,NaN,Sep 2013 - Mar 2014 · 7 mos,2013-09-01,2014-03-01,7 mos

In [136]:
df[df['duration_of_cooperation_clean'].str.contains('present', na=False)]

Empty DataFrame
Columns: [first_name, last_name, headline, job_title, time_type_full_or_part, duration_of_cooperation, location_hybrid, company_name, duration_of_cooperation_clean, start, end, duration]
Index: []

In [140]:
df.loc[:, 'end'] = df['end'].apply(lambda x: pd.to_datetime(x, format='%b %Y', errors='coerce') if x != 'Present' else 'Present')

In [144]:
df['start'] = df['start'].dt.date      
df['end'] = df['end'].apply(lambda x: x.date() if pd.notnull(x) and x != 'Present' else x)